name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: |
            echo "Hello World"
            echo "Extra input"
      - name: Print bye
        run: echo "Done bye"
